version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pip install -r requirements.txt
      - run: python setup.py sdist bdist_wheel
      - run: pip install dist/*.whl
      - run:
          command: python testing/tests/param_sweep.py
          name: Parameter sweep
      - run:
          command: python testing/tests/policy_aggregation.py
          name: Policy Aggregation
      - run:
          command: python testing/tests/multi_model_sim.py
          name: Multi Model Simulation
      - run:
          command: python testing/tests/timestep1psub0.py
          name: Timestep equals 1 instead of 0 for 1st PSUB
      - run:
          command: python testing/tests/runs_not_zero.py
          name: Value Error thrown when Runs < 1
      - run:
          command: python testing/tests/run1psub0.py
          name: Run Starts at 1 for PSUB 0
      - run:
          command: python -m unittest discover -s testing/tests -p "*_test.py"
          name: Test Suite

workflows:
  main:
    jobs:
      - test
